---
title: "Ejemplos de gráficos por ggplot2 y plotly"
author: "Nayely Araya Valerin"
format: html
toc: true
lang: es
theme: yeti
---

# Instalar paquetes

Instalación de DT
install.packages("DT")

Instalación de gapminder
install.packages("gapminder")

Instalación de más temas
install.packages("ggthemes")/
install.packages("hrbrthemes")

# Carga de paquetes

```{r}
#| label: Carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(DT)
library(knitr)
library(gapminder)
library(ggthemes)
```

# Conjunto de datos

## mpg

```{r}
#| label: tabla-mpg

mpg |>
  select(manufacturer, year, cty, hwy) |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')))
```

## diamonds

```{r}
#| label: tabla-diamonds
#| warning: false

diamonds |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## gapminder

```{r}
#| label: tabla-gapminder

gapminder |>
  datatable(
    options = list(
      pageLength = 5,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## ggplot2

```{r}
#| label: ggplot2-1

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

```{r}
#| label: ggplot2-2

mpg |>
  ggplot(aes(x = displ, y = hwy)) +
  geom_point()
```

```{r}
#| label: ggplot2-3
#| warning: false

mpg |>
  ggplot(aes(x = displ, y = hwy, colour = class)) +
  geom_point()
```

```{r}
#| label: ggplot2-4

mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, colour = class)) +
  geom_point()
```
 
```{r}
#| label: ggplot2-5

mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, color = class)) +
  geom_point() +
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6)) +
  scale_color_manual(values = c("red", "blue", "green", "purple", "orange", "brown", "pink"))
```
 
```{r}
#| label: ggplot2-6

#Gráfico de dispersión que muestre la relación entre
# el PIB per capita (x) y la esperanza de vida (y)

gapminder |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
```
 
```{r}
#| label: ggplot2-7

#Gráfico de dispersión que muestre la relación entre
# el PIB per capita (x) y la esperanza de vida (y)
# para el año 2007

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
```
 
```{r}
#| label: ggplot2-8

#Gráfico de dispersión que muestre la relación entre
# el PIB per capita (x) y la esperanza de vida (y)
# para el año 2007, con color por continente

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point()
```
 
```{r}
#| label: ggplot2-9

#Gráfico de dispersión que muestre la relación entre
# el PIB per capita (x) y la esperanza de vida (y)
# para el año 2007

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  geom_smooth()
```

```{r}
#| label: ggplot2-10
#| warning: false

#Gráfico de dispersión que muestre la relación entre
# el PIB per capita (x) y la esperanza de vida (y)
# para el año 2007

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
#| label: ggplot2-11
#| warning: false

#Gráfico de dispersión que muestre la relación entre
# el PIB per capita (x) y la esperanza de vida (y)
# para el año 2007, con color por continente

gapminder |>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point() +
  geom_smooth(method = "lm") +
  ggtitle("Relación entre PIB per capita y esperanza de vida en 2007") +
  xlab("PIB per capita EEUU ($)") +
  ylab("Esperanza de vida (años)") +
  labs(color = "Continente") +
  theme_solarized()
```




